### ISSUE TITLE
Login session does not expire after two days

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/beacon-suedtirol-administration-webapp#12]
I was logged in into the admin webapp for about two days with my admin account with a session expiration. Please set a max timeout to 1hour without user interaction.

This has been requested before, but it seems not solved yet. So please have a look, or tell us how to configure it properly, if a parameter already exists for that.

Thank you!

**Comment by raiffeisennet** [comment]
JWT Token expiration can be modified by using the config parameter

`security.jwt.token.expire-length`

**Comment by Piiit** [comment]
@raiffeisennet Thank you. I will change this inside the Jenkinsfile-Production now.

**Comment by Piiit** [comment]
@raiffeisennet A question: if I set it to 1 hour now, does the webapp re-login automatically if a user interaction has been made with the app, or will the user be kicked out?
