### ISSUE TITLE
Beacon request to show the paginated list is very slow, it downloads more than 2MB from the API currently

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/beacon-suedtirol-administration-webapp#15]
The pagination seems to be made on the Webapp only, that is, all beacons get downloaded from the API fully. The API should implement the pagination. 

Currently we need 36 seconds to get the list. We consider this a bug, since the webapp is not usable this way...

**Comment by raiffeisennet** [comment]
Pagination may be a solution for the list view, but this will not work for the map. I think there could be 2 options:

1. Use a caching mechanism so that the beacon data is fetched only on page reload and then updated in the background
2. Fetching the data incremental, e.g. fetching 10 beacons, then adding them to list/map, fetch the next and add them etc.

**Comment by raiffeisennet** [comment]
Option 2. was tested and is not comfortable to use. So option 1 will remain. Any other ideas?

The main problem is, that the fetched data has to be retrieved from the applications database and from various api calls on the manufacturers api. Without those calls, status information and beacon configuration is unavailable

**Comment by raiffeisennet** [comment]
I opened a pull request for the api. Remote beacon data (which comes through the manufacturers api) is now fetched every minute and cached in memory on server. Also ORM joining was disabled for the beacon list and replaced by using an internal HashMap. Additionally, missing gzip compressions are now enabled. The fetch time decreased from about 36s to approx. 200ms for fetching the whole list (containing 3500 beacons) by also decreasing the response size from 2Mb to 156kb.

**Comment by Piiit** [comment]
@raiffeisennet Merged and deployed. It is much better now. If we get more traffic or more beacons we need to check it again, but for now it's good. Thx.
