### ISSUE TITLE
Manage horizontal and vertical images

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-suedtirol-administration-webapp#17]
As a webapp user I want to rotate the images in order to be able to properly see both horizontal and vertical pictures.

For now the portrate vertical are shown as horizontal pictures.

![Schermata da 2019-05-28 14-35-35](https://user-images.githubusercontent.com/7909989/58478427-5c773e80-8156-11e9-9d22-3d7cd7f7f88f.png)

**Comment by Piiit** [comment]
@sseppi It this issue already resolved?
