### ISSUE TITLE
As a beacon PM I want to have beacon management app for the testing environment online, in order to be able to setup the testing beacons.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-suedtirol-administration-webapp#31]
Deadline: 16th of December 2019

- [x] Create pipeline for 
- [x] Deploy the API on https://api.beacon.testingmachine.eu
- [x] Create pipeline for https://github.com/noi-techpark/beacon-suedtirol-administration-webapp
- [x] Deploy the admin web app on https://admin.beacon.testingmachine.eu
- [x] Deploy the new beta version of the API
- [x] Deploy the new beta version of the admin web app
- [x] New beta webapp has some issues that need to be solved before we can import our new test beacons (blocked; waiting for PR by @davidebz)
- [x] Import test beacons

**Comment by Piiit** [comment]
@sseppi I put it to DONE, since we tested it during the meeting with Davide and Thomas.
