### ISSUE TITLE
As Group Manager or Beacon Editor I can't save the configuration of a Beacon of my Group

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/beacon-suedtirol-administration-webapp#46]
I'm logged in the beacon admin webapp as a Manager or Beacon Editor and I try to save a change in the configuration of a beacon assigned to my group but I receive the following error message:

"An error occured during saving. Please check your input values."

If I try to do the same operation with an Admin user the process works fine.

**Comment by Piiit** [comment]
@sseppi This should be solved now, please test all different kinds of combinations. Manager/Editor/Viewer/Admin with different groups and beacons...

https://admin.beacon.testingmachine.eu is now a 1:1 copy of the production environment

**Comment by Piiit** [comment]
@sseppi I needed to add the production kontakt.io API key, otherwise the 1:1 copy of the production DB would not work. Do we need a test kontakt.io account or would it be better to just test everything with the production one, just to be sure that then on release everything works as expected?
Do we write to that API? I do not remember details ATM... if you don't know I would need to check the source.

**Comment by sseppi** [comment]
> @sseppi This should be solved now, please test all different kinds of combinations. Manager/Editor/Viewer/Admin with different groups and beacons...
> 
> https://admin.beacon.testingmachine.eu is now a 1:1 copy of the production environment
> 
> It was a bug in the comparison of privileges, roles and groups

@Piiit now in the testing environment it seems to work fine. I've tested all user type and moreover also cross groups. So now it seems to work fine.

**Comment by sseppi** [comment]
> @sseppi I needed to add the production kontakt.io API key, otherwise the 1:1 copy of the production DB would not work. Do we need a test kontakt.io account or would it be better to just test everything with the production one, just to be sure that then on release everything works as expected?
> Do we write to that API? I do not remember details ATM... if you don't know I would need to check the source.

@Piiit We decided to not put the production kontakt.io API key in the testing environment in order to avoid the risk to misconfigure some beacon during the testings. Do you think that use the testing kontakt.io API could create problems?

**Comment by Piiit** [comment]
@sseppi Yes, we cannot test beacons that got bought with the production kontakt.io account... we can then only test beacons from the testing account. Hence, we also cannot copy/paste the production DB to testing and I cannot reproduce the exact same error as on production if I need to investigate bug reports. 
On the other hand, we are much safer if we have two accounts, but then we need to build another test setup... What do you think... both solutions have benefits and drawbacks

**Comment by sseppi** [comment]
> @sseppi Yes, we cannot test beacons that got bought with the production kontakt.io account... we can then only test beacons from the testing account. Hence, we also cannot copy/paste the production DB to testing and I cannot reproduce the exact same error as on production if I need to investigate bug reports.
> On the other hand, we are much safer if we have two accounts, but then we need to build another test setup... What do you think... both solutions have benefits and drawbacks

@Piiit but if we use the testing beacons to reproduce the errors could be an option? 

If yes, I can go to take some from the free software lab the next time that I'm in Bolzano. What do you think?

**Comment by Piiit** [comment]
@sseppi OK, so we need to delete all testing DB and set it up with only the testing beacons and testing kontakt.io account... I add a new user story for that

**Comment by sseppi** [comment]
@Piiit OK super! In the meantime do you think it would be possible to update the changes that you did on the production environment?

I see only one little problem, with the testing beacon we do not have an app to test the trusted user functionality

**Comment by Piiit** [comment]
yes, that is also a problem... I put it to production and then we open new issues for all new ideas/bugs/questions we find... ok?

**Comment by sseppi** [comment]
OK! super!

**Comment by Piiit** [comment]
@sseppi It is on production now, please re-test! :-)
